version: '3.6'
services:
  db:
    image: postgres
    container_name: coin-calculator-postgres
    environment:
      POSTGRES_PASSWORD: Qwer1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host
    networks:
      - backdb
    expose:
      - 5433
  backend:
    build:
      context: ./backend
      target:  finalApp
    image: bmertcotuk/coin-calculator:latest
    container_name: coin-calculator
    ports:
      - 8090:8090
    depends_on:
      - db
    networks:
      - frontback
      - backdb
  frontend:
    build: ./frontend/ui
    image: bmertcotuk/coin-calculator-ui:latest
    container_name: coin-calculator-ui
    ports:
      - 8080:80
    depends_on:
      - backend
    networks:
      - frontback

networks:
  backdb:
    driver: bridge
  frontback:
    driver: bridge
